CREATE DATABASE vedic_math;

USE vedic_math;


CREATE TABLE students(

id INT AUTO_INCREMENT PRIMARY KEY,

name VARCHAR(100) NOT NULL,

email VARCHAR(100) UNIQUE NOT NULL,

password VARCHAR(255) NOT NULL,

profile_pic VARCHAR(255) DEFAULT 'default.png',

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);